{
  description = "InvenTree App Development Environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs-flutter.url = "github:NixOS/nixpkgs/01fbdeef22b76df85ea168fbfe1bfd9e63681b30";
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
      nixpkgs-flutter,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config = {
            allowUnfree = true;
            android_sdk.accept_license = true;
          };
          overlays = [
            (final: prev: {
              flutter-pkg = import (self.inputs.nixpkgs-flutter) { inherit system; };
            })
          ];
        };

        androidSdk =
          (pkgs.androidenv.composeAndroidPackages {
            platformVersions = [
              "36"
              "35"
              "34"
            ];
            buildToolsVersions = [
              "36.0.0"
              "35.0.0"
              "34.0.0"
            ];
            includeNDK = true;
            ndkVersions = [ "28.2.13676358" ];
            cmakeVersions = [ "3.22.1" ];
            # sdkmanager checks more licenses than the packages we install
            # require; write them all so `flutter doctor` reports them accepted.
            extraLicenses = [
              "android-googletv-license"
              "android-googlexr-license"
              "android-sdk-arm-dbt-license"
              "android-sdk-preview-license"
              "google-gdk-license"
              "intel-android-extra-license"
              "intel-android-sysimage-license"
              "microxr-sysimage-license"
              "mips-android-sysimage-license"
            ];
          }).androidsdk;

        # The pinned nixpkgs-flutter ships a *binary* makeWrapper for
        # `$out/bin/flutter` (wrapGAppsHook3's setup hook wins over the shell
        # one), which passes `--root-certs-file='<path>'` including literal
        # quotes. Dart then fails to open the CA bundle and every network check
        # fails with "Failed to find root cert file". Re-defining makeWrapper
        # to the shell variant in postPatch (before installPhase) keeps all
        # wrapper arguments but lets bash strip the quotes at runtime.
        # engine.realm is normally written by bin/internal/update_engine_version.sh
        # on first run; the Flutter Gradle plugin reads it unconditionally.
        flutter = pkgs.flutter-pkg.flutter.overrideAttrs (old: {
          postPatch = (old.postPatch or "") + ''
            makeWrapper() { makeShellWrapper "$@"; }
          '';
          postInstall = (old.postInstall or "") + ''
            echo -n "" > $out/bin/cache/engine.realm
          '';
        });

        linuxOptionals = with pkgs; [
          gtk3
          glib
          pcre
          libepoxy
          libxkbcommon
          dbus
          at-spi2-core
          file
        ];

        fvmScript = ''
          case "$1" in
            use)
              echo "✓ Using Flutter from Nix ($(flutter --version | head -n1))"
              exit 0
              ;;
            flutter)
              shift
              exec flutter "$@"
              ;;
            dart)
              shift
              exec dart "$@"
              ;;
            *)
              echo "fvm wrapper: command '$1' not implemented (using Nix-managed Flutter)" >&2
              exit 1
              ;;
          esac
        '';
        fvm-wrapper = pkgs.writeShellScriptBin "fvm" fvmScript;
      in
      {
        devShells.default = pkgs.mkShell {
          buildInputs =
            with pkgs;
            [
              flutter
              fvm-wrapper
              jdk17
              android-tools
              gradle
              python3
              python3Packages.invoke
              jq
              git
              curl
              unzip
              which
            ]
            ++ lib.optionals stdenv.isLinux linuxOptionals;

          shellHook = ''
            export ANDROID_HOME="${androidSdk}/libexec/android-sdk"
            export ANDROID_SDK_ROOT="$ANDROID_HOME"
            export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin:$PATH"
            export JAVA_HOME="${pkgs.jdk17}"
            export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$ANDROID_HOME/build-tools/35.0.0/aapt2"

            # The Gradle wrapper is gitignored and regenerated by Flutter; its
            # shebang points into a store path that may be garbage collected,
            # which breaks `flutter build` with "No such file or directory".
            if [ -f android/gradlew ]; then
              patchShebangs android/gradlew || true
            fi
          '';

          LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath (with pkgs; linuxOptionals);
        };
      }
    );
}
