# Build Android version of the app

name: Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix (for nix usage)
        run: |
          set -euo pipefail
          curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"
          nix --version

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Collect Translation Files
        run: |
          set -euo pipefail
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"
          nix --version
          cd lib/l10n
          nix --extra-experimental-features 'nix-command flakes' develop --command python3 collect_translations.py
          cd ../..

      - name: Build Debug APK
        run: |
          set -euo pipefail
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"
          nix --version
          nix --extra-experimental-features 'nix-command flakes' develop --command flutter build apk --debug
